spring.application.name=Backend

server.port=5454

# PostgreSQL Database configuration using environment variables
spring.datasource.url=jdbc:postgresql://dpg-crupi8dumphs73an2cjg-a.singapore-postgres.render.com:5432/crudcicd
spring.datasource.username=crudcicd_user
spring.datasource.password=kckogJH9ElV3zWZkKu9J8eXHFMHfBJ24
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs (optional)
spring.jpa.show-sql=true

spring.jackson.property-naming-strategy=SNAKE_CASE

# Mail properties from environment variables
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=workknight4623@gmail.com
spring.mail.password=oxdubsidynjswzou
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
