spring.application.name=Backend

server.port=5454

# Database connection properties
spring.datasource.url=jdbc:mysql://bslmuflvel4p5bw4jevs-mysql.services.clever-cloud.com:3306/bslmuflvel4p5bw4jevs
spring.datasource.username=ucevy2mpyq80vwqu
spring.datasource.password=NcXjkjEW1mPBxwt8xICT

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs (optional)
spring.jpa.show-sql=true

spring.jackson.property-naming-strategy=SNAKE_CASE

# Mail properties from environment variables
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=workknight4623@gmail.com
spring.mail.password=oxdubsidynjswzou
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
