spring.application.name=Backend

server.port=5454

# Database connection properties
spring.datasource.url=jdbc:postgresql://dpg-cscsrlrv2p9s73fn7abg-a.singapore-postgres.render.com:5432/edutrack_ul06
spring.datasource.username=edutrack_ul06_user
spring.datasource.password=W5esUmMQ3nWYFetGJUlo57ca2dN6YqOu

# PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs (optional)
spring.jpa.show-sql=true

spring.jackson.property-naming-strategy=SNAKE_CASE

# Mail properties from environment variables
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=workknight4623@gmail.com
spring.mail.password=oxdubsidynjswzou
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
